a = input('digite algo ')
print('o tipo primitivo desse valor é ', type(a))
print('so tem espaços?', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('esta em maiuscula', a.isupper())
print('está em minuscula', a.islower())
print('esta capitalizada', a.istitle())
